---
title: "이상치제거"
author: "YounYeowon"
date: "2025-11-30"
output: html_document
---

```{r}
## Load libraries
library(tidyverse)
```

```{r}
## load data
medical <- read.csv('../mydata/clean_medical.csv')

## load etc.
cols_per_category <- readRDS('../useful/카테고리별컬럼목록.rds')
categorical_col <- readRDS('../useful/범주형변수목록.rds')
numerical_col <- readRDS('../useful/수치형변수목록.rds')

## as.factor
medical <- medical %>% 
  mutate(across(all_of(categorical_col), as.factor))
```

```{r}
is_outlier <- function(x) {
  quantiles <- quantile(x, probs = c(0.25, 0.75), na.rm = TRUE)
  Q1 <- quantiles[1]
  Q3 <- quantiles[2]
  IQR <- Q3 - Q1
  
  lower_bound <- Q1 - 1.5 * IQR
  upper_bound <- Q3 + 1.5 * IQR
  
  return(x < lower_bound | x > upper_bound)
}

medical_clean <- medical %>%
  filter(!if_any(where(is.numeric), is_outlier))

# 결과 확인
print(paste("제거 전 행 개수:", nrow(medical)))
print(paste("제거 후 행 개수:", nrow(medical_clean)))
```
```{r}
write.csv(medical_clean, '../mydata/IQR_medical.csv', row.names = FALSE)
saveRDS(medical_clean, '../mydata/IQR_medical.rds')
```

